CREATE SEQUENCE hibernate_sequence
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 6
  CACHE 1;

CREATE TABLE USER_AUTHENTICATION (
    USER_ID INTEGER PRIMARY KEY, 
    USERNAME VARCHAR,
    PASSWORD VARCHAR,
    ENABLED BOOLEAN
);

CREATE TABLE USER_AUTHORIZATION (
	USER_ROLE_ID INT PRIMARY KEY,
	USER_ID INT REFERENCES USER_AUTHENTICATION(USER_ID),
        ROLE VARCHAR
);

CREATE TABLE USER_INFORMATION (
        ID INT PRIMARY KEY,
        USER_ID INT REFERENCES USER_AUTHENTICATION(USER_ID),
        FIRST_NAME VARCHAR,
        LAST_NAME VARCHAR,
        EMAIL VARCHAR,
        PASSPORT VARCHAR, 
        IMAGE OID
);

CREATE TABLE CAR (
    ID INT PRIMARY KEY,
    BRAND VARCHAR,
    MODEL VARCHAR,
    PRICE INT,
    IMAGE OID,
    IF_EXISTS BOOLEAN
);

CREATE TABLE ORDERS (
    
)


