CREATE SEQUENCE hibernate_sequence
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 6
  CACHE 1;

CREATE TABLE USER_AUTHENTICATION (
    USER_ID INTEGER PRIMARY KEY, 
    USERNAME VARCHAR,
    PASSWORD VARCHAR,
    ENABLED BOOLEAN
);

CREATE TABLE USER_AUTHORIZATION (
	USER_ROLE_ID INT PRIMARY KEY,
	USER_ID INT REFERENCES USER_AUTHENTICATION(USER_ID),
        ROLE VARCHAR
);

CREATE TABLE USER_INFORMATION (
        ID INT PRIMARY KEY,
        USER_ID INT REFERENCES USER_AUTHENTICATION(USER_ID),
        EMAIL VARCHAR,
        PASSPORT VARCHAR
);

INSERT INTO USER_AUTHENTICATION VALUES(1,'alpha','$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', TRUE);
INSERT INTO USER_AUTHORIZATION VALUES(1,1,'ROLE_ADMIN');
